wryun/es-shell

Makefile.in, configure.ac
See Issue #12 (Error when installing to new directory).
Add the autoconf test AC_PROG_MKDIR_P.
Use MKDIR_P to ensure intermediate directories exist before running install.
=> Create directory paths before calling install.

heredoc.c
After glibc upgrade (I think) one of my scripts started to complain about null variable in here document.
The following may or may not reproduce the problem for you, but `sealcountedbuffer(buf)` frees its argument so using `buf->len` afterwards is illegal.
```
; cat a
{} << X
$a
X
; es a
a:3: null variable name in here document
```
=> Fix use after free in heredoc variables

Makefile.in
Software distributions use DESTDIR to install the software contents
to a separate locaiton that is packaged into a package.
Currently being tested.
=> Makefile.in: Respect DESTDIR on install target.

print.c, stdenv.h
As the code already assumes that va_start and va_end exists (even when stdarg_h is not defined) i think that using va_copy by default won't cause any regression, but to guarantee i added some defines when stdarg_h is not defined (those definitions works because the compiler export __va_*)
Also should fix issue #24 (actually i'm not sure, as the person said that changing to va_copy weren't enough, but in my machine i was able to build it with musl)
edit: i tested on adelie linux, and in fact the master branch compiles with this minimal change
=> Always use va_copy (musl support)

access.c, es.h, main.c, opt.c, prim-etc.c
When I filed #60 I forgot that es already has built-in option parsing!  So for consistency and concision's sake let's use that for main() as well.
Seems to work with trip.es and GCDEBUG (when built on top of #52).
I tried a much more extreme change to main and other es entry points in https://github.com/jpco/es-shell/blob/es-main/runtime.es#L219 but couldn't get the exact behavior right :/
This fixes #60.  Should be otherwise completely transparent to users.
=> Use esopt() for option parsing in main

es.h, input.c, prim.c, stdenv.h, var.c
This is a little incomplete -- it doesn't handle complex var syntax like `$(x y z)`, and much more importantly, it does not include command completion at all.  Command completion would need significant cleverness and effort on its own to handle the fact that `%pathsearch` is a hook.
=> Add readline completion for variables, primitives, and usernames prefixed with `~`

.circleci/config.yml
This should help find fresh memory/ref bugs before they get merged.
I set the values via make command-line flags mostly for expediency -- if it's preferable to do something in `./configure` or similar, I'll happily do that.
=> Use stricter build flags in circleci's es build.

closure.c, eval.c, syntax.c
```
; '%closure ()'
```
was a segfault; now is a syntax error exception.  Fixes #68 
```
; () x
```
was an assertion error; now is not an error at all (the null term is just thrown away).  Fixes #63 
```
; let (n = '%closure (x = y) echo $x') {$n}
```
printed `y y` before; now correctly prints `y`.  Fixes #57
=> Fix syntax-handling bugs

input.c
I don't know how I missed this the first time around.  A file with a single quote character (') in it should be quoted.
=> Quote files which contain '.

configure.ac
Fix building with autoconf 2.72.  Resolves #77, where more detail is provided on what this fix does.
This also swaps out `egrep` for `grep -E` in `./configure`, which shuts up a warning but doesn't actually make the fix happen.
Comparing `configure.ac` against the autoconf docs, I notice there's a lot of stuff in there that's "obsolescent".  Should we go through and clean up there?  Does it make sense to keep trying so hard to be portable that even the portability tool thinks it's too much?
=> Add AC_PROG_CPP to configure.ac

es.h, except.c, gc.c, var.c
This fixes a (niche) class of memory unsafety.
We define a new root list to support this, because the two existing root lists won't work: rootlist is stack-oriented, while the e variable during throw() is being carried backwards through the stack; and globalrootlist (reasonably) has no mechanism for removing a root, which is necessary for the very ephemeral exception lists.
Fixes #85.
=> Root exceptions during the varpop() calls in throw().

var.c
=> Clean up after exceptions in varpop().

README.md
Should be:
https://wryun.github.io/es-shell/
not:
https://wryun.github.com/es-shell/
=> README.md: fix GitHub Pages url

es.h, input.c, syntax.c
Some declarations appeared after executable code in both #59 and #36, which caused issues for compilers that don't support that C99 feature.
Newer compilers on modern systems may complain about the K&R-style getenv replacement code when it's enabled, mainly because of the lack of const-correctness since K&R lacked a `const` keyword.
Nobody uses K&R anymore, and K&R-style function declarations and definitions have been dropped entirely as of C23 as well, so everything gets proper prototypes and function definitions, including gcisblocked() in es.h.
Also, implicit function declarations were removed in C99, so a prototype for initgetenv() has been added to es.h for compatibility.
=> Compilation fixes

input.c
Fixes #111.
Previously, signals received but not triggering an exception (so, signals handled with the `sig_noop` handler) at the prompt would cause the shell to exit on an `eof` exception.  This is a minimal fix for that.
=> Fix /signal handling with readline

doc/es.1
This change inspired by playing around with PDF-formatted man pages via `man -Tpdf es`.
- Set update date to "now" because the man page has actually changed quite a few times since March 1992 :)
- Consistent subsection capitalization
- A couple just straight up bug fixes
- A couple style changes from monospace text into italic text which seem more consistent with the rest of the doc
- Some prose changes to the "Matching Multiple Patterns" subsection
- Moved the `$matchexpr` bit into the "Matching Multiple Patterns" subsection to match `$bqstatus`
- Used `.ta` to get a consistent indentation across formats for the example `match subject`.  (The spacing isn't ideal in the PDF version, but it's at least consistent between the two lines.)
I'm still not 100% sure where the "Matching Multiple …
=> Nitpicky changes to man page.

input.c
(Re-)fixes #111.  The problem with the first fix attempt in #113 is that it changed the code that calls `callreadline()` from thinking a `NULL` return value _always_ means EOF to thinking it _never_ does.  In fact, it _sometimes_ does!  So this version is a little more nuanced, only setting `errno = EINTR` in `callreadline()` when a signal has interrupted things.
I will be less hasty this time and not submit this myself, even though I think it's a fairly uncontroversial bug fix ("surely _this time_ it'll work...")
As an aside, I kind of think `/signame` should actually just `SIG_IGN` the signal in the local process and re-set it to `SIG_DFL` in `setsigdefaults()`.  Seems like the most straightforward thing, and no more racey than the other signal behaviors already being handled by …
=> Fix ^\ handling with readline, without breaking ^D handling with readline.

input.c
This causes %exit-on-false, as part of %dispatch, to be the actual trigger for the exit-on-false behavior.  The implementation context strongly implies that the current behavior is a bug.  (Why would we use %exit-on-false, whose only job is to set eval_exitonfalse to 1, and also just leave eval_exitonfalse as 1 ourselves?  Why would we explicitly call `$fn-%dispatch false` in the `error` exception handler if we expected a simple call to `false` to exit the shell too?)
This also makes using `es -e` with any kind of overriden REPL much easier, because %prompt and other REPL hooks can no longer trigger the exit-on-false behavior.
This is one part of #73, but because this part is almost definitely just a bug, while the rest is more about design improvements, I am merging this part more …
=> Clear eval_exitonfalse when setting up a new input stream.

heredoc.c, input.c, input.h
Fixes #100.
This simple version works both when sending a ^D while reading a heredoc at the interactive loop, and when falling off the end of a shell script while reading a heredoc.
=> Do not die when reading incomplete heredocs

eval.c
Fixes #5, I think.
Behavior without:
```
; $&a.
es panic: eval: bad closure node kind 3
```
Behavior with:
```
; $&a.
invalid primitive: $&a^.
```
=> Fix panic when trying to eval concatted prims.

initial.es
I believe the fact that `%background` returns the PID of the process it creates is an oversight.
- It only happens as a side-effect of assigning `apid` to the new PID.
- The function has not changed since the "assignment returns the value" change went into effect.
- Other shells (including, most relevantly, _rc_) return true from `command &`
- It would be consistent with other cases where the "assignment returns the value" change had knock-on effects (see #70).
- It is entirely redundant to set `$apid`, print the new PID if interactive, _and_ return the PID
- In general there is a convention in _es_ commands that they either produce output by returning it, or by printing it/performing side effects, and there is a pattern of defining functions (e.g., `var`) which echo the value returned …
=> Return true instead of the new PID from %background

es.h, eval.c, prim-ctl.c, prim-etc.c, prim-sys.c, status.c
`true` and `false` have been made into keywords in C23, so this PR renames those `List *` variables to `ltrue` and `lfalse` to allow compilation with C23 compilers.
_XS_ previously did the same since they were keywords in C++ already, so this is mostly a C23 compatibility fix to allow _es_ to still compile whenever compiler vendors make C23 the default standard.
Judging by the gap of 3-4 years between C11/C17 being published and `-std=gnu11/-std=gnu17` becoming the default in GCC and Clang, i expect those two compiler suites will make `-std=gnu23` the default in 2028 at the latest.
=> Rename true/false -> ltrue/lfalse

dict.c, fd.c, match.c
This fixes an out-of-bounds read operation in `rangematch()`, a bit-shift operation on a negative value (undefined behavior), and pointer arithmetic on a null pointer (undefined behavior).
=> Fix rangematch() and a couple of undefined behavior issues

dump.c, es.h, eval.c, except.c, input.c, main.c, match.c, prim-etc.c, prim-io.c, prim.h, print.c, signal.c, stdenv.h, token.c, var.c
tl;dr
* `unused` macro renamed to `UNUSED` for consistency with macros like `STMT` and `NOP`
* `noreturn(F)` macro and `noreturn` typedef consolidated into a single macro `Noreturn`
* New `FALLTHROUGH` macro to indicate explicit fallthrough to GCC-compatible compilers that will otherwise warn about it when a flag like `-Wimplicit-fallthrough` is enabled
* `UNUSED`, `Noreturn`, and `FALLTHROUGH` are now conditionally defined.
- - -
I renamed `unused` to `UNUSED` since other macros like `STMT` and `NOP` use all-caps names.
I also used the attribute name `__unused__` in place of `unused` so that any potential `unused` macro already defined wouldn't expand `__attribute__((unused))` to something like `__attribute__((__attribute__((__unused__))))`.
I realize the name change is a slightly …
=> Update code related to compiler attributes

.gitignore, Makefile.in, configure.ac, doc/es.1, es.h, esconfig.h, initial.es, input.c, m4/readline.m4, prim-etc.c, stdenv.h, token.c, var.c
This corrects a bug where `--with-readline=no/--without-readline` doesn't actually disable readline.
These days, shared libs are also used, so `-lreadline` alone is usually sufficient with the shared libreadline pulling in the necessary curses/terminfo/termcap lib (that's likely how this bug went unnoticed for so long).
In the event that static linking is required, however, linker tests are performed to determine which lib to link with, adding the first of `-lcurses`, `-ltinfo`, `-lterminfo`, or `-ltermcap` that links with a readline program and `-lreadline` successfully.
If `--with-readline=yes/--with-readline` is specified and the linker test fails in all of the above cases, which may also be due to incorrect CFLAGS resulting in failing to find `readline/readline.h` and …
=> Fix --without-readline and link with curses/terminfo/termcap correctly

Makefile.in
The VPATH feature used in the Makefile allows building _es_ outside `$(srcdir)`.
Without this, both the `test` and `install` targets fail due to their use of `$(srcdir)/es` when the current directory differs from `$(srcdir)`.
=> Fix VPATH builds

doc/es.1, es.h, initial.es, input.c, prim-etc.c
1. Do not do so unless actually necessary (that is, either when we call `callreadline()` or when we change the value again later).
2. Shrink stifle_history size to 5000.
Both of these speed up startup quite a bit, and both also reduce memory usage quite a bit as well.  The first one is an unambiguous win; the second may be unfortunate for those folks who want to search some very old commands.  Does anyone want a `$max-history-size` variable so as to have a choice in the matter?
Also, I'll repeat my question from the linked issue: Should we clear the in-memory history when $history is changed?
This fixes #133 (edit: it also fixes #135).
=> Reduce performance impact of reading history.

Makefile.in, input.c, main.c, var.c
Fairly mechanical.  `char **volatile argv` is certainly a sign your program is doing something good.
=> Enable -Wclobbered and resolve all warnings.

var.c
This is a relatively simple change that addresses #127.  It implements the suggestion in the mailing list here: http://wryun.github.io/es-shell/mail-archive/msg00837.html
As discussed in #127, settor functions on startup still have some pitfalls with this change.  Unfortunately, there's probably no perfect way to invoke settors on startup; the zero-flake fix would be to avoid running settors on startup at _all_, and instead establish some kind of `%init` hook function on startup that can implement the same behavior in a more deterministic way.  But that's a backwards-incompatible change that requires some real design consideration.  This change makes things at least somewhat better without any breaking changes or novel design work required.  (Concretely, it fixes the ability to define a …
=> Delay settor invocation at startup

parse.y, syntax.c, syntax.h
This PR removes the confusing `treecons`/`treecons2` and `treeconsend`/`treeconsend2` distinction by always using the `2` versions of the functions (and giving them the non-`2` names).  This makes `parse.y`, in my opinion, much simpler to understand.
The user-visible impact of this change is that _es_ now more robustly deduplicates thunks:
```
; ./es.old -c 'echo {(({({{}})}))}'
{{{}}}
; ./es.new -c 'echo {(({({{}})}))}'
{}
```
Additionally, this removes several other (very minor) cases of redundancy in ASTs:
```
; ./es.old -Lnc '$(a ((b) c))'
(list (var (list (word "a") (list (list (word "b")) (word "c")))))
; ./es.new -Lnc '$(a ((b) c))'
(list (var (list (word "a") (word "b") (word "c"))))
; ./es.old -Lnc 'if (({false} {false}) {true})'
(list (word "if") (list (list (thunk (list (word …
```
=> Simplify ASTs generated from redundant lists and thunks

access.c
Closes #126.
This also fixes a bug when the `-1` flag was not specified.
The same error message buffer used by `esstrerror()` was reused for all error messages, so the same pointer was mistakenly added to the list of results multiple times:
```
; paths = /usr/bin /tmp/nonexistent/missing
; echo <={access -w $paths}
No such file or directory No such file or directory
; paths = $paths(2) $paths(1)
; echo <={access -w $paths}
Permission denied Permission denied
```
This also meant an `access -1e` invocation that throws an exception would somehow appear to change the error string obtained from a previous `access` invocation without `-1`:
```
; x = <={access -w $paths(1)}
; var x
x = 'No such file or directory'
; access -1e -w $paths(2)
Permission denied
; var x
x = 'Permission denied'
```
=> Make `$&access` match all permissions

INSTALL, Makefile.in, doc/es.1, share/autoload.es, share/cdpath.es, share/interactive-init.es, share/path-cache.es, share/status.es
This change adds five scripts which represent commonly-desired features to _es_ which, by default, probably shouldn't live in the shell, but also should be available for those who want them.
The novel aspect here is these scripts are installed by `make install` to `$prefix/share/es` (and, I imagine, should be packaged along with the binary as well).  They are also mentioned in the man page.
A note to reviewers: I don't intend these to be "show off jpco's setup" scripts.  That would go in `examples/` (not to mention I don't even use half of these most of the time!).  The intent here is to be authoritative: if you want this feature, this is probably how you'd want it.  So, if you _do_ happen to use any of these features, would you be willing to switch to the "canonical" versions provided …
=> Add canonical extensions

prim-io.c, proc.c
Don't attempt to close an fd we know is invalid; also bother to `free()` the proclist on a fork.
Neither of these are fixes for any real issues.
=> Small nitpicks caught by valgrind.

prim-io.c, print.c, print.h, str.c, test/tests/wait.es
Fixes #93.  Fixes #99.
Throwing an exception from `$&read` when getting a null byte is kind of weak, but it's strictly better than crashing.  In the future I expect we can figure out a way to actually handle null bytes intelligently, but there are a few options there and none of them are the obviously-best one.
The error-handling for `write`s is also a little sketchy; half the time we ignore the error from `fprint_flush`, assuming that if there are any problems, the final `flush` will run into them too and we'll handle them then.  Also, in many cases I expect that if stderr is closed or broken, the shell with this change will throw exceptions into exiting (without printing anything), which overall isn't much more helpful than its current behavior of just quietly `exit(2)`ing.  I think …
=> Fix a couple crashing cases by throwing exceptions instead.

configure.ac, doc/es.1, es.h, eval.c, gc.c, main.c, open.c, prim-io.c, prim-sys.c, print.c, proc.c, signal.c, stdenv.h, test/tests/wait.es, util.c
This PR is stuff that's a bit difficult to reason about, since outside of job control, process group related changes are basically only visible through side effects.  This description describes the state for all POSIX-compliant OSes (in particular, those with `setsid()`.)
State before:
- The `$&newpgrp` primitive places _es_ into its own session, and attempts to take the terminal for the new process group implicitly created with the new session, which always quietly fails.
- If built with `JOB_PROTECT`, then _es_ places every new background process into a new session.  This causes certain "shell-spawning" processes like terminals and window managers to fail to kill those backgrounded processes when they exit.  This can be useful, but is nonstandard and often undesirable.
State after:
- …
=> Use POSIX-compatible setpgid()

configure.ac
@memreflect (reasonably) suggested using `$ac_cv_header_stdc` to verify whether the `AC_HEADERS_STDC` check passed.  That's consistent with the autoconf 2.67 documentation.  However, it seems that since autoconf 2.70 (based on docs) and certainly in autoconf 2.72 (based on testing), that cache variable no longer gets defined.  If I create a minimal configure.ac
```
AC_INIT
AC_HEADER_STDC
```
and build and run `./configure` using autoconf 2.72, then `config.log` includes the following cache variables:
```
ac_cv_c_compiler_gnu=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set= …
```
=> Don't depend on $ac_cv_header_stdc being available

es.h, input.c, prim-sys.c, proc.c
Fixes #151 (introduced with #128) and #152 (introduced with #143).
`getrusage()` has been pulled out of `proc.c` entirely and is now managed within `$&time`.  I think this structure is a lot better in terms of separation-of-concerns.  It's also nicely simple to implement with how `getrusage()` works, which is something that seemed very weird to me at first.  So that's nice!
It occurs to me with this change that if we make use of `getrusage(RUSAGE_SELF)` as well, we could actually `$&time` commands without forking, which seems like an interesting possibility.  If you have a slow-running script, you could just wrap whole sections inside a `time {}` without any disruption to the script's function...  Even better, it looks like the standard `times()` also supports getting times from the …
=> Fixes for recently-introduced readline and `$&time` bugs

doc/es.1
- Use `\(ha`, `\(aq`, and `\(ga` to get correctly-rendered ^, ', and ` in all cases
- Fix "lo ... hi" to include spaces
- Add period to `$^path.` which I erroneously removed before
- Remove `throw` from the `match` command example, since exceptions haven't been explained at that point in the doc
- Move the flatten-backtick example from the variable-flattening to the command-substitution section
- Describe the return value of a pipeline more specifically
- Change "signal catcher" to "exception catcher"
- Add `max-eval-depth` and `max-history-length`
- Update `%eval-noprint` and friends to refer to `%dispatch` instead of being arguments to the REPL functions
=> Nitpicky changes to man page

initial.es, share/status.es
Fixes #145.
- `eval` is noreturn, so `@ {eval return 1; return 2}` appropriately returns 1.
- `%eval-print` is noreturn, so `es -xc 'return 99'` behaves like `es -c 'return 99'` does.
- Non-primitive `%readfrom` and `%writeto` are noreturn, so `return <{true}` behaves consistently in both primitive and non-primitive forms.
- `share/status.es` sets `$status` based on return exceptions, and keeps `%dispatch` noreturn.
Not so related to return: `true` and `false` don't include their arguments in their return value, such that `true blah` returns `0` instead of `0 blah`, which is falsey.
=> Small fixes, mostly around return

doc/es.1
Better formatting for double quotes with `\(lq` and `\(rq`.
Use `\(ti` to make sure that `man(1)` outputs a proper ASCII tilde character.  This goes along with the `\(ha`, `\(aq`, and `\(ga` changes in #156 to help guarantee that code snippets provided in the rendered man page can be copy-pasted into a terminal and run.  (These changes are more visible when the page is rendered as a PDF with `man -Tpdf es > es.pdf`.)
All based on tips in the Portability section in `man 7 groff_man_style`.
I think I've finally run out of nitpicks for the man page :)
=> Even more man page nitpicks

configure.ac, gc.c, input.c, main.c, match.c, prim.c, prim.h, print.c, stdenv.h, var.c
This modifies the GCDEBUG stuff to be more standards-compliant.  It removes the (nonfunctional, it turns out, on both macOS and the Hurd) special-cased mach stuff, changes the `caddr_t` to a `void *`, accounts for `MAP_ANONYMOUS` vs. `MAP_ANON`, and adds fallback behavior in case mmap() or mprotect() are missing.  I tested that the fallback behavior still causes the shell to quickly implode when memory bugs are present.  So this fixes #155.  At the same time I added a fallback from `va_copy` to `__va_copy` to fix #157.
Tested on my usual set of OSes -- the Hurd, FreeBSD, Haiku, Omni OS, and Linux -- and on all of them `-DGCDEBUG=1` works, both with and without `-ansi -D_POSIX_C_SOURCE=200112L -DNSIG=28`.  I also tested macOS, and it works with `-DGCDEBUG=1`, but with the ansi flags, …
=> Make `-ansi -D_POSIX_C_SOURCE=200112L -DGCDEBUG=1` work

prim-ctl.c, test/tests/option.es
Found while looking at #73; `if` "turns off" the exit-on-false behavior when running each `test`, but the current behavior has it also do so while running the `else` command, which seems pretty clearly wrong.
```
if {false} {
command which will not run
} {
commands that might
be risky
don''''t you want
some -e protection here?
}
```
The fact that this has never been reported before is, along with the fact that the bodies of `while` loops run with `eval_exitonfalse` toggled off, is pretty compelling evidence to me that nobody ever uses `-e`...
=> Fix $&if to run "elses" like "thens", not "tests"

es.h, main.c, signal.c, test/tests/trip.es
With this PR, if a `signal sigfoo` exception is not caught, it causes the shell to die with a `sigfoo`, if the signal can do that.  This resolves the following inconsistency:
```
; echo <={es.old -c 'kill -term $pid'}
terminated
sigterm
; echo <={es.old -c 'signals = sigterm; kill -term $pid'}
uncaught exception: signal sigterm
1
```
See:
```
; echo <={es.new -c 'kill -term $pid'}
terminated
sigterm
; echo <={es.new -c 'signals = sigterm; kill -term $pid'}
terminated
sigterm
```
This does not change in which cases a signal causes a shell to exit, just the exit status of the shell in those cases where it does.  Fixes #112.
This PR revealed to me (but didn't cause) a couple small bugs with signal handling that I'd like to address separately:
1. The command `kill -$SIG $pid` in a shell that …
=> Exit with signal status if a signal exception reaches the top level

conv.c
```
; es.old -c 'echo {~ x ()}'
{~ x }
; es.new -c 'echo {~ x ()}'
{~ x}
```
```
; es.old -c 'echo @ {}; echo @ * {}'
@ * {}
@ *{}
; es.new -c 'echo @ {}; echo @ * {}'
@ *{}
@ *{}
```
```
; es.old -c 'echo {$(a b)}'
{$((a b))}
; es.new -c 'echo {$(a b)}'
{$(a b)}
```
```
; es.old -c 'echo {$()}'
{$}
; es.new -c 'echo {$()}'
{$()}
```
I don't love all these choices personally (I'd rather `{~ x ()}` than `{~ x}` and `@ * {}` rather than `@ *{}`), but concision is pretty valuable when stuffing these strings into the environment, so I won't fight too hard to add more characters than strictly necessary (Adding parens to `{$}` is necessary because `{$}` isn't actually valid syntax).
=> Small fixes/improvements to printed trees

conv.c
Reverts wryun/es-shell#162
It introduced a bug: `{$(a^$b)}` became `{$a^$b}`.
=> Revert "Small fixes/improvements to printed trees"

conv.c, test/tests/syntax.es
Small changes.
```
; es.old -c 'echo {@ {}} {@ * {}}'
{@ * {}} {@ *{}}
; es.new -c 'echo {@ {}} {@ * {}}'
{@ *{}} {@ *{}}
; es.old -c 'echo {~ a ()}'
{~ a }
; es.new -c 'echo {~ a ()}'
{~ a}
; es.old -c 'echo {$()}'
{$}
; es.new -c 'echo {$()}'
{$()}
; es.old -c 'echo {$(a)}'
{$(a)}
; es.new -c 'echo {$(a)}'
{$a}
; es.old -c 'echo {$(a b)}'
{$((a b))}
; es.new -c 'echo {$(a b)}'
{$(a b)}
; es.old -c 'echo {$(a b)}'
{$((a b))}
; es.new -c 'echo {$(a b)}'
{$(a b)}
```
Also add some test cases this time to avoid the kinds of regressions introduced in #162.  Most of these changes are for aesthetics and also serve to shorten the output (good for strings in the environment). The `{$()}` case is simply a bug fix.
=> Small changes to printed trees -- take 2

es.h, input.c, var.c
No user impact, pure code reorganization.  This is a piece of #178.  The location of `LOCAL_GETENV` in input.c is because it supports readline, but ideally we should move away from readline being "the library that _es_ uses" and toward "_es_ supports using different libraries according to what users want."
=> Move LOCAL_GETENV handling to var.c where the other env handling lives.

test/tests/trip.es, token.c
It would be nice if we could have this (both signed and unsigned chars) checked automatically, but the only way I can think of to do that would get into a "build and test with multiple sets of CFLAGS", which is more than I'd want to get into at the moment.  I'm a little surprised there isn't some GCC or Clang warning that caught this for us.  `-Wconversion` does, but enabling that opens a much larger can of worms in another way.
This change also allows for extra characters at the end of permissions strings in `trip.es`.  Helps address the majority of #187, I believe, aside from `cat` behaving weird, which I don't think is an _es_ issue.
=> Handle EOF in scanerror instead of infinite-looping

prim-io.c, util.c
The callers of these functions are already doing their own `SIGCHK()`s as appropriate, and in certain cases we want to do these calls without `SIGCHK()`ing.
Fixes the following issue:
```
; echo `{es -c 'signals = -sigint; echo <=%read'}
^C
;
```
Now that terminal is all messed up because the `es -c` process is still running and trying to read from it.
```
; echo `{./es -c 'signals = -sigint; echo <=%read'}
^C^C^C^C^C^Cblah
; 
```
The parent _es_ no longer "abandons" its child, the child gets reaped when it actually exits, and everything stays reasonable.
You may note that the `blah` read by the child isn't actually echoed by the parent.  That seems to happen when a sigint is sent.  This seems to happen in every shell's equivalent of the ``echo `{}`` syntax though (and I tested with a …
=> Remove SIGCHK() from eread() and ewrite().

var.c
GNU Readline 4.3 on stock OpenBSD 7.6 uses `putenv()`, but the allocated string `envname` in `putenv()` was not properly null-terminated, leading to readline trying to set incorrect environment variable names like `LINES{garbage bytes}`.
=> Fix string handling bug in putenv()

input.c, input.h
When bison is run with `POSIXLY_CORRECT`, it errors out if `yyerror` doesn't take a `const char *`.  Technically I believe it's right -- according to POSIX, this parameter should be `const`.
=> Make the char *s involved in yyerror const

prim-etc.c, test/tests/regression.es
=> Ref() syntax errors thrown from $&parse

INSTALL
- Removed the HP-UX note, as I suspect it's no longer accurate.
- Added instructions for OpenBSD which should address #184.  We may be better off not expecting the more recent readline functionality, but I don't know either way on that.
- Added mention of `--with-readline` and `--without-readline`, and removed mention of editline, which I believe we have essentially given up on.
- Mentioned the requirement for POSIX.1-2001.
=> Update INSTALL instructions and add OpenBSD to them

INSTALL
`mandir` for 3rd-party software is `/usr/local/man` on OpenBSD,
whereas with `mandir` at `/usr/local/share/man`,
`man es` won't work
=> Update INSTALL - OpenBSD ./configure --mandir

signal.c
This obsoletes the `TRUST_INCOMING_SIGNAL_HANDLERS` define by making it always apply.
Previously, _es_ would crash if it started up with any signal handler set other than `SIG_DFL` or `SIG_IGN`.  This blocked certain development tools like asan and gprof, so I added this build flag in #167 to help those cases.  However, it seems certain targets these days also use this to simply use the shell normally (see #183), so it's worth making it the default.
Fixes #183.
=> Trust startup signals by default

initial.es
`vars` is fairly ancient and predates some of the nice stuff we have today, like lexically-scoped functions and the `~~` operator.  Using those -- especially `~~` -- lets us do more "getopt"-ish argument parsing.
=> Update vars so that its option parsing is less "primitive"

es.h, gc.c, gc.h, heredoc.c, input.c, input.h, prim-etc.c, str.c, syntax.c, syntax.h, token.c, tree.c
This change itself does not change anything for the user -- as far as I can tell, it doesn't even have a noticeable performance or memory-use impact to speak of.  It does add some code complexity, but I believe it's worth it.
The upside of this change is that it removes the major technical blocker for running _es_ functions while fetching input -- meaning that things like programmable key bindings, completions, line-by-line history-writing (as opposed to the per-command history writing after #65), and more (see #178) are all now possible with this change.
How it works is that it defines a new memory "space" called "pspace", where any parser-related GC-like memory allocations go.  Unlike normal GC space, pspace is never automatically collected, and is in fact manually collected at the end …
=> Allocate memory from the parser in "pspace", not GC space

access.c, history.c, prim-io.c
- Use some libc return values (seen when building with -D_FORTIFY_SOURCE=2)
- function defined as func() => func(void)
Related to #3.
=> Fix minor compiler complaints

match.c, test/tests/glob.es
Fixes #208.
This resolves a performance corner-case that I'm not sure anyone has ever actually hit, but at the same time it mildly simplifies the `match()` algorithm in a satisfying way.
Also adds a few test cases for matching against these patterns.
Verified performance benefit:
```
; touch aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
; es.old -c 'time {echo a*a*a*a*a*a*a*b}'
a*a*a*a*a*a*a*b
39r    39.5u     0.0s	{echo a*a*a*a*a*a*a*b}
; es.new -c 'time {echo a*a*a*a*a*a*a*b}'
a*a*a*a*a*a*a*b
0r     0.0u     0.0s	{echo a*a*a*a*a*a*a*b}
```
=> "Fix" backtracking performance blow-up in globbing

eval.c, test/testrun.c, test/tests/trip.es
Very picky, very niche change.  Found while thinking about `path-cache.es` and a notion of "aliases" that I've been playing around with.
Here is a script which demonstrates the change.
```
let (fn-sh = ()) sh -c 'echo $0'
let (fn-sh = /bin/sh) sh -c 'echo $0'
let (ps = $fn-%pathsearch)
fn %pathsearch bin {
if {~ $bin print-dollar-0} {
result <={$ps sh} -c 'echo $0'
} {
$ps $bin
}
}
print-dollar-0
```
At head this script prints (on my machine):
```
sh
/bin/sh
/usr/bin/sh
```
In this fork this script prints:
```
sh
sh
print-dollar-0
```
There are two effects going on here:
- if we set `fn-name = /path/to/bin`, then running `name` will invoke `/path/to/bin` with `$0` set to `name`.
- if we redefine `%pathsearch` such that `%pathsearch name` returns `/path/to/bin some args`, then running …
=> Track and use the "function name" for $0 in forked binaries

eval.c, gc.c, prim-io.c, term.c
This PR changes `GCALWAYS` to trigger a GC on every (non-GC-blocked) call to `gcenable()`.  This reveals a few memory bugs which have been lurking.  This started when I started running into one particular bug in a repeatable way; the rest of this first comment describes the fix for that one issue, before I got more to the bottom of all this.
---
I don't fully understand the issue here (nor do I have a testable repro), but this fixes a memory bug manifesting as segfaults and closure assertion failures, caused, I believe, by bad ordering between lvalue evaluation and GC.  Adding a temp variable forces the right thing to happen.
As I see it, the issue can be illustrated with the following minimal example in C:
```c
#include <stdlib.h>
#include <stdio.h>
int *s;
int set(int i) {
s = …
```
=> Make GCALWAYS GC more, and fix memory bugs

es.h, input.c, prim-io.c, signal.c, util.c
This should resolve #224.
We remove the `slow`/`slowlabel` wrapping around `read` and `write`, which is unnecessary on POSIX.1-2001 compliant systems.  This helps simplify some code, and could lead to more-correct behavior, given the `slow`/`slowlabel` wrapping was problematic when used with `waitpid`.  This leaves this behavior only used with `readline()`; jumping out of the signal handler seems to be the best (and only?) way to exit from `readline()` calls when receiving signals.
We also remove the `interrupted` variable, as it seems redundant with surrounding code.  This helps simplify control flow and (slightly) reduces the number of globals.
It might be nice to get `slow` and `slowlabel` removed entirely, but I believe the complexity that would add to `readline()` invocation would be …
=> Reduce use of, and simplify, slow syscall handling
